apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: tap-network
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "tap-network",
      "type": "tap-plugin",
      "ipam": {
          "type": "host-local",
          "subnet": "192.168.1.0/24",
          "routes": [
              { "dst": "0.0.0.0/0" }
          ]
      }
  }'
